/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as Tournament2048ContractJson } from "../Tournament2048.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import * as types from "./types";
import { RalphMap } from "@alephium/web3";

// Custom types for the contract
export namespace Tournament2048Types {
  export type Fields = {
    baseEntryFee: bigint;
    entryGrowthNumerator: bigint;
    entryGrowthDenominator: bigint;
    inactivityResetWindowMs: bigint;
    payoutBps: bigint;
    carryBps: bigint;
    currentEntryFee: bigint;
    pot: bigint;
    roundIndex: bigint;
    lastActivityAt: bigint;
    totalRuns: bigint;
    totalSubmissions: bigint;
    leaderboardTopScore: bigint;
    leaderboardTopPlayer: Address;
  };

  export type State = ContractState<Fields>;

  export type RunStartedEvent = ContractEvent<{
    runIdHash: HexString;
    player: Address;
    seedHash: HexString;
    startedAt: bigint;
    roundIndex: bigint;
    entryFee: bigint;
    potAfter: bigint;
    totalRuns: bigint;
  }>;
  export type RunSubmittedEvent = ContractEvent<{
    runIdHash: HexString;
    player: Address;
    score: bigint;
    attestationHash: HexString;
    submittedAt: bigint;
    roundIndex: bigint;
    payout: bigint;
    carry: bigint;
  }>;
  export type InactivityResetEvent = ContractEvent<{
    triggeredAt: bigint;
    roundIndexBefore: bigint;
    topScoreBefore: bigint;
  }>;

  export interface CallMethodTable {
    nextEntryFee: {
      params: CallContractParams<{ currentFee: bigint }>;
      result: CallContractResult<bigint>;
    };
    maybeResetForInactivity: {
      params: CallContractParams<{ now: bigint }>;
      result: CallContractResult<null>;
    };
    startRun: {
      params: CallContractParams<{
        runIdHash: HexString;
        seedHash: HexString;
        payment: bigint;
      }>;
      result: CallContractResult<null>;
    };
    submitScore: {
      params: CallContractParams<{
        runIdHash: HexString;
        score: bigint;
        attestationHash: HexString;
      }>;
      result: CallContractResult<null>;
    };
    getEconomyState: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<
        [
          bigint,
          bigint,
          bigint,
          bigint,
          bigint,
          bigint,
          bigint,
          Address,
          bigint
        ]
      >;
    };
    getRunState: {
      params: CallContractParams<{ runIdHash: HexString }>;
      result: CallContractResult<
        [boolean, Address, HexString, bigint, boolean, bigint, HexString]
      >;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    nextEntryFee: {
      params: SignExecuteContractMethodParams<{ currentFee: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    maybeResetForInactivity: {
      params: SignExecuteContractMethodParams<{ now: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    startRun: {
      params: SignExecuteContractMethodParams<{
        runIdHash: HexString;
        seedHash: HexString;
        payment: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    submitScore: {
      params: SignExecuteContractMethodParams<{
        runIdHash: HexString;
        score: bigint;
        attestationHash: HexString;
      }>;
      result: SignExecuteScriptTxResult;
    };
    getEconomyState: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getRunState: {
      params: SignExecuteContractMethodParams<{ runIdHash: HexString }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];

  export type Maps = { runs?: Map<HexString, types.RunReceipt> };
}

class Factory extends ContractFactory<
  Tournament2048Instance,
  Tournament2048Types.Fields
> {
  encodeFields(fields: Tournament2048Types.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      types.AllStructs
    );
  }

  eventIndex = { RunStarted: 0, RunSubmitted: 1, InactivityReset: 2 };
  consts = {
    BPS_DENOMINATOR: BigInt("10000"),
    LOCKED_BASE_ENTRY: BigInt("1000000000000000000"),
    LOCKED_GROWTH_NUM: BigInt("11"),
    LOCKED_GROWTH_DEN: BigInt("10"),
    LOCKED_RESET_MS: BigInt("86400000"),
    LOCKED_PAYOUT_BPS: BigInt("5000"),
    LOCKED_CARRY_BPS: BigInt("5000"),
    ErrorCodes: {
      RunNotOwnedByCaller: BigInt("0"),
      RunIdMismatch: BigInt("1"),
      RunAlreadySubmitted: BigInt("2"),
      InvalidEntryPayment: BigInt("3"),
      InvalidEconomyConfig: BigInt("4"),
      InvalidLockedParams: BigInt("5"),
      RunAlreadyStarted: BigInt("6"),
    },
  };

  at(address: string): Tournament2048Instance {
    return new Tournament2048Instance(address);
  }

  tests = {
    nextEntryFee: async (
      params: TestContractParams<
        Tournament2048Types.Fields,
        { currentFee: bigint },
        Tournament2048Types.Maps
      >
    ): Promise<TestContractResult<bigint, Tournament2048Types.Maps>> => {
      return testMethod(this, "nextEntryFee", params, getContractByCodeHash);
    },
    maybeResetForInactivity: async (
      params: TestContractParams<
        Tournament2048Types.Fields,
        { now: bigint },
        Tournament2048Types.Maps
      >
    ): Promise<TestContractResult<null, Tournament2048Types.Maps>> => {
      return testMethod(
        this,
        "maybeResetForInactivity",
        params,
        getContractByCodeHash
      );
    },
    startRun: async (
      params: TestContractParams<
        Tournament2048Types.Fields,
        { runIdHash: HexString; seedHash: HexString; payment: bigint },
        Tournament2048Types.Maps
      >
    ): Promise<TestContractResult<null, Tournament2048Types.Maps>> => {
      return testMethod(this, "startRun", params, getContractByCodeHash);
    },
    submitScore: async (
      params: TestContractParams<
        Tournament2048Types.Fields,
        { runIdHash: HexString; score: bigint; attestationHash: HexString },
        Tournament2048Types.Maps
      >
    ): Promise<TestContractResult<null, Tournament2048Types.Maps>> => {
      return testMethod(this, "submitScore", params, getContractByCodeHash);
    },
    getEconomyState: async (
      params: Omit<
        TestContractParams<
          Tournament2048Types.Fields,
          never,
          Tournament2048Types.Maps
        >,
        "args"
      >
    ): Promise<
      TestContractResult<
        [
          bigint,
          bigint,
          bigint,
          bigint,
          bigint,
          bigint,
          bigint,
          Address,
          bigint
        ],
        Tournament2048Types.Maps
      >
    > => {
      return testMethod(this, "getEconomyState", params, getContractByCodeHash);
    },
    getRunState: async (
      params: TestContractParams<
        Tournament2048Types.Fields,
        { runIdHash: HexString },
        Tournament2048Types.Maps
      >
    ): Promise<
      TestContractResult<
        [boolean, Address, HexString, bigint, boolean, bigint, HexString],
        Tournament2048Types.Maps
      >
    > => {
      return testMethod(this, "getRunState", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: Tournament2048Types.Fields,
    asset?: Asset,
    address?: string,
    maps?: Tournament2048Types.Maps
  ) {
    return this.stateForTest_(initFields, asset, address, maps);
  }
}

// Use this object to test and deploy the contract
export const Tournament2048 = new Factory(
  Contract.fromJson(
    Tournament2048ContractJson,
    "=12+3b4=1+7=3-1=1-2=1-1=2-2+19=158-2+70=296+7a7e0214696e73657274206174206d617020706174683a2000=1080",
    "69c24a5be61aae6a3a2d4f7fa876590f95e2b979a8ff0eafb33333c35873bacb",
    types.AllStructs
  )
);
registerContract(Tournament2048);

// Use this class to interact with the blockchain
export class Tournament2048Instance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  maps = {
    runs: new RalphMap<HexString, types.RunReceipt>(
      Tournament2048.contract,
      this.contractId,
      "runs"
    ),
  };

  async fetchState(): Promise<Tournament2048Types.State> {
    return fetchContractState(Tournament2048, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeRunStartedEvent(
    options: EventSubscribeOptions<Tournament2048Types.RunStartedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Tournament2048.contract,
      this,
      options,
      "RunStarted",
      fromCount
    );
  }

  subscribeRunSubmittedEvent(
    options: EventSubscribeOptions<Tournament2048Types.RunSubmittedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Tournament2048.contract,
      this,
      options,
      "RunSubmitted",
      fromCount
    );
  }

  subscribeInactivityResetEvent(
    options: EventSubscribeOptions<Tournament2048Types.InactivityResetEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Tournament2048.contract,
      this,
      options,
      "InactivityReset",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      | Tournament2048Types.RunStartedEvent
      | Tournament2048Types.RunSubmittedEvent
      | Tournament2048Types.InactivityResetEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(
      Tournament2048.contract,
      this,
      options,
      fromCount
    );
  }

  view = {
    nextEntryFee: async (
      params: Tournament2048Types.CallMethodParams<"nextEntryFee">
    ): Promise<Tournament2048Types.CallMethodResult<"nextEntryFee">> => {
      return callMethod(
        Tournament2048,
        this,
        "nextEntryFee",
        params,
        getContractByCodeHash
      );
    },
    maybeResetForInactivity: async (
      params: Tournament2048Types.CallMethodParams<"maybeResetForInactivity">
    ): Promise<
      Tournament2048Types.CallMethodResult<"maybeResetForInactivity">
    > => {
      return callMethod(
        Tournament2048,
        this,
        "maybeResetForInactivity",
        params,
        getContractByCodeHash
      );
    },
    startRun: async (
      params: Tournament2048Types.CallMethodParams<"startRun">
    ): Promise<Tournament2048Types.CallMethodResult<"startRun">> => {
      return callMethod(
        Tournament2048,
        this,
        "startRun",
        params,
        getContractByCodeHash
      );
    },
    submitScore: async (
      params: Tournament2048Types.CallMethodParams<"submitScore">
    ): Promise<Tournament2048Types.CallMethodResult<"submitScore">> => {
      return callMethod(
        Tournament2048,
        this,
        "submitScore",
        params,
        getContractByCodeHash
      );
    },
    getEconomyState: async (
      params?: Tournament2048Types.CallMethodParams<"getEconomyState">
    ): Promise<Tournament2048Types.CallMethodResult<"getEconomyState">> => {
      return callMethod(
        Tournament2048,
        this,
        "getEconomyState",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getRunState: async (
      params: Tournament2048Types.CallMethodParams<"getRunState">
    ): Promise<Tournament2048Types.CallMethodResult<"getRunState">> => {
      return callMethod(
        Tournament2048,
        this,
        "getRunState",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    nextEntryFee: async (
      params: Tournament2048Types.SignExecuteMethodParams<"nextEntryFee">
    ): Promise<Tournament2048Types.SignExecuteMethodResult<"nextEntryFee">> => {
      return signExecuteMethod(Tournament2048, this, "nextEntryFee", params);
    },
    maybeResetForInactivity: async (
      params: Tournament2048Types.SignExecuteMethodParams<"maybeResetForInactivity">
    ): Promise<
      Tournament2048Types.SignExecuteMethodResult<"maybeResetForInactivity">
    > => {
      return signExecuteMethod(
        Tournament2048,
        this,
        "maybeResetForInactivity",
        params
      );
    },
    startRun: async (
      params: Tournament2048Types.SignExecuteMethodParams<"startRun">
    ): Promise<Tournament2048Types.SignExecuteMethodResult<"startRun">> => {
      return signExecuteMethod(Tournament2048, this, "startRun", params);
    },
    submitScore: async (
      params: Tournament2048Types.SignExecuteMethodParams<"submitScore">
    ): Promise<Tournament2048Types.SignExecuteMethodResult<"submitScore">> => {
      return signExecuteMethod(Tournament2048, this, "submitScore", params);
    },
    getEconomyState: async (
      params: Tournament2048Types.SignExecuteMethodParams<"getEconomyState">
    ): Promise<
      Tournament2048Types.SignExecuteMethodResult<"getEconomyState">
    > => {
      return signExecuteMethod(Tournament2048, this, "getEconomyState", params);
    },
    getRunState: async (
      params: Tournament2048Types.SignExecuteMethodParams<"getRunState">
    ): Promise<Tournament2048Types.SignExecuteMethodResult<"getRunState">> => {
      return signExecuteMethod(Tournament2048, this, "getRunState", params);
    },
  };

  async multicall<Calls extends Tournament2048Types.MultiCallParams>(
    calls: Calls
  ): Promise<Tournament2048Types.MultiCallResults<Calls>>;
  async multicall<Callss extends Tournament2048Types.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<Tournament2048Types.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | Tournament2048Types.MultiCallParams
      | Tournament2048Types.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      Tournament2048,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
