// MVP placeholder for Alephium generated artifacts export.
// In full setup this file is generated by @alephium/web3 and compiler outputs.

export const Tournament2048Artifact = {
  contractName: 'Tournament2048',
  source: './contracts/Tournament2048.ral',
  methods: [
    {
      name: 'startRun',
      params: ['runIdHash', 'seedHash']
    },
    {
      name: 'submitScore',
      params: ['runIdHash', 'score', 'attestationHash']
    }
  ]
};
